export const projects = [
  {
    id: 14,
    title: "run.ilo",
    category: "ai",
    description: "Community directory of runs, fun runs, and marathons in Iloilo City.",
    longDescription:
      "A community-driven platform for discovering and listing runs, fun runs, and marathons in Iloilo City, Philippines. Built with Next.js, Supabase (Postgres + Row Level Security), and Leaflet with OpenStreetMap for interactive race route maps — no API key required. Features an admin review workflow for community-submitted events and a demo mode with bundled sample data for zero-setup exploration.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Leaflet", "OpenStreetMap"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb/run-ilo",
    featured: true,
    completed: "2026",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Built a community race directory with Next.js App Router and Supabase",
      "Integrated Leaflet and OpenStreetMap for interactive route maps",
      "Implemented admin review workflow for community-submitted events",
      "Added demo mode with bundled sample data for zero-setup exploration",
    ],
  },
  {
    id: 15,
    title: "Lead Point",
    category: "ai",
    description: "AI-powered business website demo with embedded chatbot and appointment booking.",
    longDescription:
      "A full-stack business website demo built to showcase how AI chat assistants and appointment booking workflows can be integrated into a modern service business site. The demo features service listings, team bios, patient testimonials, and an embedded AI chat widget that handles customer inquiries and books appointments — demonstrating a production-ready pattern for AI-enhanced lead capture.",
    technologies: ["Next.js", "TypeScript", "Supabase", "PostgreSQL", "Tailwind CSS"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "https://lead-point-chi.vercel.app",
    githubUrl: "https://github.com/asrnb/lead-point",
    featured: false,
    completed: "2026",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Built a full-stack business site demo with Next.js and Supabase",
      "Integrated an AI chat assistant for customer inquiries and appointment booking",
      "Demonstrated a production-ready pattern for AI-enhanced lead capture",
      "Designed for zero-friction deployment as a reusable business template",
    ],
  },
  {
    id: 4,
    title: "Computer Vision Dress Code Compliance",
    category: "ai",
    description: "Computer vision thesis project for detecting dress code violations.",
    longDescription:
      "A computer vision-based system for detecting dress code compliance among WVSU students. The thesis project used Python, Flask, YOLOv8, OpenCV, and SQLite, with April leading ideation, topic selection, and front-end development.",
    technologies: ["Python", "Flask", "YOLOv8", "OpenCV", "SQLite"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb",
    featured: false,
    completed: "2025",
    teamSize: 4,
    difficulty: 4,
    achievements: [
      "Applied YOLOv8 and OpenCV to a campus compliance use case",
      "Designed a Flask-based web application",
      "Used SQLite for lightweight local data handling",
      "Led ideation and UI/UX direction for the thesis project",
    ],
  },
  {
    id: 5,
    title: "Sentiment Analyzer Web Application",
    category: "ai",
    description: "Real-time NLP web app for sentiment analysis.",
    longDescription:
      "A real-time sentiment analysis web application built with Python, Flask, NLP techniques, HTML, CSS, and JavaScript. The app analyzes text input and returns sentiment insights through a simple web interface.",
    technologies: ["Python", "Flask", "NLP", "HTML", "CSS", "JavaScript"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb",
    featured: false,
    completed: "2024",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Built a Flask web interface for real-time text analysis",
      "Applied NLP methods to classify sentiment",
      "Designed a lightweight front end with HTML, CSS, and JavaScript",
      "Created a practical demonstration of AI-assisted text understanding",
    ],
  },
  {
    id: 6,
    title: "BizGen GPT",
    category: "ai",
    description: "AI-powered business idea generator for entrepreneurs.",
    longDescription:
      "A Streamlit app built for CCS 229 that uses OpenAI's GPT model to help entrepreneurs generate business ideas. Users pick an industry (Technology, Healthcare, Education, Retail, Finance, or Food & Beverage), a target audience, and unique selling points, and the app generates tailored, ready-to-use business concepts for instant feedback or team brainstorming.",
    technologies: ["Python", "Streamlit", "OpenAI", "Prompt Engineering"],
    imageUrl: "/projects/bizgen-gpt-cover.png",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb/ccs229-finalproject",
    featured: false,
    completed: "2024",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Created a business ideation workflow powered by OpenAI GPT",
      "Built an interactive Streamlit interface",
      "Designed prompts for industry-specific idea generation",
      "Focused on practical support for early-stage entrepreneurs",
    ],
  },
  {
    id: 11,
    title: "Luminance",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called Luminance, designed end-to-end in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "https://www.figma.com/proto/2hdvz905hpaX5xcBkUAykF/Luminance--UI-UX-?node-id=1-4&t=g5Iveeu5jCV242C8-1",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the Luminance app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
  {
    id: 12,
    title: "Sa-kai",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called Sa-kai, designed in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "https://www.figma.com/proto/EBbrqTIt5OCmmTp9RXDALV/Sa-kai?node-id=3-652&starting-point-node-id=1%3A4",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the Sa-kai app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
  {
    id: 13,
    title: "TuklaSEEn",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called TuklaSEEn, designed in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl:
      "https://www.figma.com/proto/LZM9lghc147nd1RaHMoBwB/TuklaSEEn-Prototype?node-id=11-130&t=vWAL2a06wzsdVRds-1&starting-point-node-id=11%3A130",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the TuklaSEEn app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
]

export function hasRealImage(imageUrl: string) {
  return Boolean(imageUrl) && !imageUrl.startsWith("/placeholder")
}
