export const projects = [
  {
    id: 14,
    title: "run.ilo",
    category: "ai",
    description: "Community directory of runs, fun runs, and marathons in Iloilo City.",
    longDescription:
      "A community-driven platform for discovering and listing runs, fun runs, and marathons in Iloilo City, Philippines. Built with Next.js, Supabase (Postgres + Row Level Security), and Leaflet with OpenStreetMap for interactive race route maps — no API key required. Features an admin review workflow for community-submitted events and a demo mode with bundled sample data for zero-setup exploration.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Leaflet", "OpenStreetMap"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb/run-ilo",
    featured: true,
    completed: "2026",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Built a community race directory with Next.js App Router and Supabase",
      "Integrated Leaflet and OpenStreetMap for interactive route maps",
      "Implemented admin review workflow for community-submitted events",
      "Added demo mode with bundled sample data for zero-setup exploration",
    ],
  },
  {
    id: 15,
    title: "Lead Point",
    category: "ai",
    description: "AI-powered business website demo with embedded chatbot and appointment booking.",
    longDescription:
      "A full-stack business website demo built to showcase how AI chat assistants and appointment booking workflows can be integrated into a modern service business site. The demo features service listings, team bios, patient testimonials, and an embedded AI chat widget that handles customer inquiries and books appointments — demonstrating a production-ready pattern for AI-enhanced lead capture.",
    technologies: ["Next.js", "TypeScript", "Supabase", "PostgreSQL", "Tailwind CSS"],
    imageUrl: "/projects/lead-point.png",
    demoUrl: "https://lead-point-asrnb.vercel.app/",
    githubUrl: "https://github.com/asrnb/lead-point",
    featured: false,
    completed: "2026",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Built a full-stack business site demo with Next.js and Supabase",
      "Integrated an AI chat assistant for customer inquiries and appointment booking",
      "Demonstrated a production-ready pattern for AI-enhanced lead capture",
      "Designed for zero-friction deployment as a reusable business template",
    ],
  },
  {
    id: 17,
    title: "ContentFlow AI",
    category: "ai",
    description: "Asynchronous AI content generation SaaS with dashboard observability.",
    longDescription:
      "A production-oriented SaaS app for authenticated users to queue AI content generation jobs and inspect the full asynchronous lifecycle from request to result. Built with Next.js, Supabase Auth and PostgreSQL, Row Level Security, Inngest background jobs, Anthropic structured output, Zod validation, retry handling, execution timelines, and automated test coverage.",
    technologies: ["Next.js", "TypeScript", "Supabase", "Inngest", "Anthropic", "Zod", "Vitest"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb/callflow-ai",
    featured: false,
    completed: "2026",
    teamSize: 1,
    difficulty: 4,
    achievements: [
      "Built an authenticated dashboard for queuing AI content generation jobs",
      "Implemented asynchronous processing with Inngest and persisted execution events",
      "Secured user-owned data with Supabase Auth, PostgreSQL, and Row Level Security",
      "Validated structured Anthropic output with Zod and covered core flows with Vitest and Playwright",
    ],
  },
  {
    id: 16,
    title: "AttendEase",
    category: "software",
    description: "Event attendee check-in app with registration and duplicate check-in prevention.",
    longDescription:
      "A focused event check-in system built with Next.js and Supabase. Attendees enter a phone number to check in, returning attendees are matched from the database, and new attendees can register with their name before being checked in. The app prevents duplicate check-ins, keeps a live unique attendee count, validates names and phone numbers, and wraps the flow in a responsive neo-brutalist interface for fast on-site event use.",
    technologies: ["Next.js", "React", "Supabase", "JavaScript", "CSS Modules"],
    imageUrl: "/attend-ease.png",
    demoUrl: "https://attend-ease-vert.vercel.app/",
    githubUrl: "https://github.com/asrnb/attend-ease",
    featured: false,
    completed: "2026",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Built a phone-based event check-in flow with Next.js",
      "Connected Supabase tables for attendees and check-in records",
      "Prevented duplicate attendee check-ins with database lookups",
      "Added registration, validation, cooldown handling, and a live unique check-in count",
    ],
  },
  {
    id: 4,
    title: "Computer Vision Dress Code Compliance",
    category: "ai",
    description: "Computer vision thesis project for detecting dress code violations.",
    longDescription:
      "A computer vision-based system for detecting dress code compliance among WVSU students. The thesis project used Python, Flask, YOLOv8, OpenCV, and SQLite, with April leading ideation, topic selection, and front-end development.",
    technologies: ["Python", "Flask", "YOLOv8", "OpenCV", "SQLite"],
    imageUrl: "/projects/thesis-dress-code-compliance.jpg",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb",
    featured: false,
    completed: "2025",
    teamSize: 4,
    difficulty: 4,
    achievements: [
      "Applied YOLOv8 and OpenCV to a campus compliance use case",
      "Designed a Flask-based web application",
      "Used SQLite for lightweight local data handling",
      "Led ideation and UI/UX direction for the thesis project",
    ],
  },
  {
    id: 5,
    title: "Sentiment Analyzer Web Application",
    category: "ai",
    description: "Real-time NLP web app for sentiment analysis.",
    longDescription:
      "A real-time sentiment analysis web application built with Python, Flask, NLP techniques, HTML, CSS, and JavaScript. The app analyzes text input and returns sentiment insights through a simple web interface.",
    technologies: ["Python", "Flask", "NLP", "HTML", "CSS", "JavaScript"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb",
    featured: false,
    completed: "2024",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Built a Flask web interface for real-time text analysis",
      "Applied NLP methods to classify sentiment",
      "Designed a lightweight front end with HTML, CSS, and JavaScript",
      "Created a practical demonstration of AI-assisted text understanding",
    ],
  },
  {
    id: 6,
    title: "BizGen GPT",
    category: "ai",
    description: "AI-powered business idea generator for entrepreneurs.",
    longDescription:
      "A Streamlit app built for CCS 229 that uses OpenAI's GPT model to help entrepreneurs generate business ideas. Users pick an industry (Technology, Healthcare, Education, Retail, Finance, or Food & Beverage), a target audience, and unique selling points, and the app generates tailored, ready-to-use business concepts for instant feedback or team brainstorming.",
    technologies: ["Python", "Streamlit", "OpenAI", "Prompt Engineering"],
    imageUrl: "/projects/bizgen-gpt-cover.png",
    demoUrl: "https://ccs229-finalproject-fehdbadqzl3hwir3ehqp4q.streamlit.app/",
    githubUrl: "https://github.com/asrnb/ccs229-finalproject",
    featured: false,
    completed: "2024",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Created a business ideation workflow powered by OpenAI GPT",
      "Built an interactive Streamlit interface",
      "Designed prompts for industry-specific idea generation",
      "Focused on practical support for early-stage entrepreneurs",
    ],
  },
  {
    id: 11,
    title: "Luminance",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called Luminance, designed end-to-end in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/luminance.png",
    demoUrl:
      "https://www.figma.com/proto/75s1qguqruFXB3p5fV5Ooa/Group-4-Luminance---Suarnaba---de-Leon---Calinagan---Montalban---Jagunap?node-id=1-4",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the Luminance app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
  {
    id: 12,
    title: "Sa-kai",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called Sa-kai, designed in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/sakaii.png",
    demoUrl:
      "https://www.figma.com/proto/EBbrqTIt5OCmmTp9RXDALV?node-id=0-1&fuid=949944370631712677&prev-plan-id=949944380634869785&prev-plan-type=team&prev-selected-view=recentsAndSharing&prev-tab=recently-viewed",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the Sa-kai app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
  {
    id: 13,
    title: "TuklaSEEn",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called TuklaSEEn, designed in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/tuklaseen.png",
    demoUrl:
      "https://www.figma.com/proto/LZM9lghc147nd1RaHMoBwB/TuklaSEEn-Prototype?node-id=0%3A1&fuid=949944370631712677",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the TuklaSEEn app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
]

export function hasRealImage(imageUrl: string) {
  return Boolean(imageUrl) && !imageUrl.startsWith("/placeholder")
}
