export const projects = [
  {
    id: 1,
    title: "SEO & AI Grader",
    category: "ai",
    description:
      "SEO analytics dashboard pulling live data from GA4, Search Console, and Ahrefs.",
    longDescription:
      "A full-stack SEO dashboard built with Vue 3, Vite, and Tailwind on the frontend with an Express backend. It pulls live metrics from Google Analytics 4, Google Search Console, and Ahrefs, scores Technical SEO Health, and lets teams filter by date range and report period, then export the full dashboard as a PDF.",
    technologies: ["Vue 3", "Vite", "Tailwind", "Express", "Pinia", "PrimeVue", "Google OAuth"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb/seo-grader",
    featured: true,
    completed: "2025",
    teamSize: 1,
    difficulty: 4,
    achievements: [
      "Built a full-stack dashboard with Vue 3, Vite, Tailwind, and Express",
      "Integrated GA4, Google Search Console, and Ahrefs data via OAuth",
      "Built Technical SEO Health scoring with cached first-crawl baselines",
      "Added PDF export of the full dashboard for client reporting",
    ],
  },
  {
    id: 2,
    title: "HubSpot LinkedIn Automation Workflows",
    category: "ai",
    description: "CRM automation workflows using HubSpot custom code, APIs, and Lambda.",
    longDescription:
      "Scalable automation workflows for LinkedIn outreach and CRM operations. The system uses HubSpot custom code, HubSpot APIs, Node.js, and Lambda to automate message flows, persona detection, tagging, and contact/deal associations.",
    technologies: ["HubSpot APIs", "Node.js", "Lambda", "CRM Automation", "LinkedIn"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 4,
    achievements: [
      "Developed scalable CRM automation workflows",
      "Built dynamic LinkedIn message automation",
      "Implemented persona detection and tagging logic",
      "Automated deal and contact association systems",
    ],
  },
  {
    id: 4,
    title: "Computer Vision Dress Code Compliance",
    category: "ai",
    description: "Computer vision thesis project for detecting dress code violations.",
    longDescription:
      "A computer vision-based system for detecting dress code compliance among WVSU students. The thesis project used Python, Flask, YOLOv8, OpenCV, and SQLite, with April leading ideation, topic selection, and front-end development.",
    technologies: ["Python", "Flask", "YOLOv8", "OpenCV", "SQLite"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb",
    featured: false,
    completed: "2025",
    teamSize: 4,
    difficulty: 4,
    achievements: [
      "Applied YOLOv8 and OpenCV to a campus compliance use case",
      "Designed a Flask-based web application",
      "Used SQLite for lightweight local data handling",
      "Led ideation and UI/UX direction for the thesis project",
    ],
  },
  {
    id: 5,
    title: "Sentiment Analyzer Web Application",
    category: "ai",
    description: "Real-time NLP web app for sentiment analysis.",
    longDescription:
      "A real-time sentiment analysis web application built with Python, Flask, NLP techniques, HTML, CSS, and JavaScript. The app analyzes text input and returns sentiment insights through a simple web interface.",
    technologies: ["Python", "Flask", "NLP", "HTML", "CSS", "JavaScript"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb",
    featured: false,
    completed: "2024",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Built a Flask web interface for real-time text analysis",
      "Applied NLP methods to classify sentiment",
      "Designed a lightweight front end with HTML, CSS, and JavaScript",
      "Created a practical demonstration of AI-assisted text understanding",
    ],
  },
  {
    id: 6,
    title: "BizGen GPT",
    category: "ai",
    description: "AI-powered business idea generator for entrepreneurs.",
    longDescription:
      "A Streamlit app built for CCS 229 that uses OpenAI's GPT model to help entrepreneurs generate business ideas. Users pick an industry (Technology, Healthcare, Education, Retail, Finance, or Food & Beverage), a target audience, and unique selling points, and the app generates tailored, ready-to-use business concepts for instant feedback or team brainstorming.",
    technologies: ["Python", "Streamlit", "OpenAI", "Prompt Engineering"],
    imageUrl: "/projects/bizgen-gpt-cover.png",
    demoUrl: "",
    githubUrl: "https://github.com/asrnb/ccs229-finalproject",
    featured: false,
    completed: "2024",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Created a business ideation workflow powered by OpenAI GPT",
      "Built an interactive Streamlit interface",
      "Designed prompts for industry-specific idea generation",
      "Focused on practical support for early-stage entrepreneurs",
    ],
  },
  {
    id: 11,
    title: "Luminance",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called Luminance, designed end-to-end in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "https://www.figma.com/proto/2hdvz905hpaX5xcBkUAykF/Luminance--UI-UX-?node-id=1-4&t=g5Iveeu5jCV242C8-1",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the Luminance app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
  {
    id: 12,
    title: "Sa-kai",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called Sa-kai, designed in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl: "https://www.figma.com/proto/EBbrqTIt5OCmmTp9RXDALV/Sa-kai?node-id=3-652&starting-point-node-id=1%3A4",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the Sa-kai app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
  {
    id: 13,
    title: "TuklaSEEn",
    category: "design",
    description: "UI/UX app design with an interactive Figma prototype.",
    longDescription:
      "An application UI/UX design project called TuklaSEEn, designed in Figma with a clickable interactive prototype covering the app's core screens and user flow.",
    technologies: ["Figma", "UI/UX Design", "Prototyping"],
    imageUrl: "/placeholder.svg?height=600&width=800",
    demoUrl:
      "https://www.figma.com/proto/LZM9lghc147nd1RaHMoBwB/TuklaSEEn-Prototype?node-id=11-130&t=vWAL2a06wzsdVRds-1&starting-point-node-id=11%3A130",
    githubUrl: "",
    featured: false,
    completed: "2025",
    teamSize: 1,
    difficulty: 3,
    achievements: [
      "Designed the TuklaSEEn app's UI/UX from scratch in Figma",
      "Built an interactive, clickable prototype for the core user flow",
      "Defined a consistent visual and interaction language across screens",
    ],
  },
]

export function hasRealImage(imageUrl: string) {
  return Boolean(imageUrl) && !imageUrl.startsWith("/placeholder")
}
